export const assignmentData = [
  {
    id: 1,
    title: "Design new ui presentation",
    project: "Digital Project",
    progress: 3,
    total: 10,
    date: "24 Aug 2025",
    avatars: [
      "https://github.com/shadcn.png",
      "https://randomuser.me/api/portraits/women/68.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    status: "todo",
  },
  {
    id: 2,
    title: "Design new ui presentation",
    project: "Digital Project",
    progress: 3,
    total: 10,
    date: "24 Aug 2025",
    avatars: [
      "https://github.com/shadcn.png",
      "https://randomuser.me/api/portraits/women/68.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    status: "todo",
  },
  {
    id: 3,
    title: "Design new ui presentation",
    project: "Digital Project",
    progress: 3,
    total: 10,
    date: "24 Aug 2025",
    avatars: [
      "https://github.com/shadcn.png",
      "https://randomuser.me/api/portraits/women/68.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    status: "todo",
  },
  {
    id: 4,
    title: "Design new ui presentation",
    project: "Digital Project",
    progress: 3,
    total: 10,
    date: "24 Aug 2025",
    avatars: [
      "https://github.com/shadcn.png",
      "https://randomuser.me/api/portraits/women/68.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    status: "todo",
  },
  {
    id: 5,
    title: "Design new ui presentation",
    project: "Digital Project",
    progress: 3,
    total: 10,
    date: "24 Aug 2025",
    avatars: [
      "https://github.com/shadcn.png",
      "https://randomuser.me/api/portraits/women/68.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    status: "todo",
  },
  {
    id: 6,
    title: "Design new ui presentation",
    project: "Digital Project",
    progress: 3,
    total: 10,
    date: "24 Aug 2025",
    avatars: [
      "https://github.com/shadcn.png",
      "https://randomuser.me/api/portraits/women/68.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    status: "progress",
  },
  {
    id: 7,
    title: "Design new ui presentation",
    project: "Digital Project",
    progress: 3,
    total: 10,
    date: "24 Aug 2025",
    avatars: [
      "https://github.com/shadcn.png",
      "https://randomuser.me/api/portraits/women/68.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    status: "progress",
  },
  {
    id: 8,
    title: "Design new ui presentation",
    project: "Digital Project",
    progress: 3,
    total: 10,
    date: "24 Aug 2025",
    avatars: [
      "https://github.com/shadcn.png",
      "https://randomuser.me/api/portraits/women/68.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    status: "progress",
  },
  {
    id: 9,
    title: "Design new ui presentation",
    project: "Digital Project",
    progress: 3,
    total: 10,
    date: "24 Aug 2025",
    avatars: [
      "https://github.com/shadcn.png",
      "https://randomuser.me/api/portraits/women/68.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    status: "progress",
  },
  {
    id: 10,
    title: "Design new ui presentation",
    project: "Digital Project",
    progress: 3,
    total: 10,
    date: "24 Aug 2025",
    avatars: [
      "https://github.com/shadcn.png",
      "https://randomuser.me/api/portraits/women/68.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    status: "progress",
  },
  {
    id: 11,
    title: "Design new ui presentation",
    project: "Digital Project",
    progress: 10,
    total: 10,
    date: "24 Aug 2025",
    avatars: [
      "https://github.com/shadcn.png",
      "https://randomuser.me/api/portraits/women/68.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    status: "completed",
  },
  {
    id: 12,
    title: "Design new ui presentation",
    project: "Digital Project",
    progress: 10,
    total: 10,
    date: "24 Aug 2025",
    avatars: [
      "https://github.com/shadcn.png",
      "https://randomuser.me/api/portraits/women/68.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    status: "completed",
  },
  {
    id: 13,
    title: "Design new ui presentation",
    project: "Digital Project",
    progress: 10,
    total: 10,
    date: "24 Aug 2025",
    avatars: [
      "https://github.com/shadcn.png",
      "https://randomuser.me/api/portraits/women/68.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    status: "completed",
  },
  {
    id: 14,
    title: "Design new ui presentation",
    project: "Digital Project",
    progress: 10,
    total: 10,
    date: "24 Aug 2025",
    avatars: [
      "https://github.com/shadcn.png",
      "https://randomuser.me/api/portraits/women/68.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    status: "completed",
  },
];
